use std::net::SocketAddr;
use std::path::PathBuf;

use clap::{crate_description, crate_version, value_parser};
use clap::{Arg, Command};
use crate::app::{CRATE_BIN_NAME, CRATE_REPOSITORY};

pub fn build_cli() -> Command {
    let app_description: &str = crate_description!();
    Command::new(CRATE_BIN_NAME)
        .version(crate_version!())
        .about(format!("{} \n{}", app_description, CRATE_REPOSITORY))
        .allow_external_subcommands(true)
        .subcommand(Command::new("config")
            .about("Set global configuration")
            .arg(Arg::new("node-id")
                .help("Generate a new node ID")
                .long("node-id")
                .num_args(0)
            )
            .arg(Arg::new("cert")
                .help("Path to the certificate file (PEM or DER format)")
                .long("cert")
                .value_name("file-path")
                .value_parser(value_parser!(PathBuf))
            )
            .arg(Arg::new("key")
                .help("Path to the private key file (PEM or DER format)")
                .long("key")
                .value_name("file-path")
                .value_parser(value_parser!(PathBuf))
            )
            .arg(Arg::new("relay")
                .help("Relay server address")
                .long("relay")
                .value_name("socket-addr")
                .value_parser(value_parser!(SocketAddr))
            )
            .arg(Arg::new("output")
                .help("Output dir path")
                .long("output")
                .value_name("dir-path")
                .value_parser(value_parser!(PathBuf))
            )
            .arg(Arg::new("temp")
                .help("Temp dir path")
                .long("temp")
                .value_name("dir-path")
                .value_parser(value_parser!(PathBuf))
            )
            .arg(Arg::new("conn-timeout")
                .help("Connection timeout in seconds")
                .long("conn-timeout")
                .value_name("duration-in-seconds")
                .value_parser(value_parser!(u64))
            )
            .arg(Arg::new("read-timeout")
                .help("Read timeout in seconds")
                .long("read-timeout")
                .value_name("duration-in-seconds")
                .value_parser(value_parser!(u64))
            )
            .arg(Arg::new("write-timeout")
                .help("Write timeout in seconds")
                .long("write-timeout")
                .value_name("duration-in-seconds")
                .value_parser(value_parser!(u64))
            )
            .arg(Arg::new("read-buffer-size")
                .help("Read buffer size in bytes")
                .long("read-buffer-size")
                .value_name("size-in-bytes")
                .value_parser(value_parser!(u64))
            )
            .arg(Arg::new("write-buffer-size")
                .help("Write buffer size in bytes")
                .long("write-buffer-size")
                .value_name("size-in-bytes")
                .value_parser(value_parser!(u64))
            )
            .arg(Arg::new("log-level")
                .help("Log level")
                .long("log-level")
                .value_name("level")
                .value_parser(value_parser!(String))
            )
        )
        .subcommand(Command::new("send")
            .about("Send a file")
        )
        .subcommand(Command::new("receive")
            .about("Receive a file")
        )
        .subcommand(Command::new("connect")
            .about("Connect to a server")
        )
        .subcommand(Command::new("listen")
            .about("Listen for incoming connections")
        )
}
